#!/bin/sh
DGW_SRC=../html/xml/src/
DGW_DST=../html
i=screenshot$1

cd ../xml2html
ilrun dghtml.exe -i ${DGW_SRC}/$i.xml -o ${DGW_DST}/$i.html -t ${DGW_SRC}/template_html4.xml -p ./${DGW_SRC}/
ilrun dghtml.exe -i ${DGW_SRC}/$i.xml -o ${DGW_DST}/html2.0/$i.html -t ${DGW_SRC}/template_html2.xml -p ./${DGW_SRC}/ -r ../

